input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Burada loglarınıza özel filtreler ekleyebilirsiniz.
  # IP adreslerinden coğrafi konum bilgisi ekler
  geoip {
    source => "client_ip"
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTIC_HOSTS}"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "ft_transcendence-%{+YYYY.MM.dd}"
  }
  # Hata ayıklama için logları konsola yazdırır
  stdout { codec => rubydebug }
}